FROM node:20.8.1 as builder

WORKDIR /src/
COPY frontend/calories/ /src/

RUN npm install

RUN npm run build

FROM nginx

COPY frontend/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /src/dist/ /usr/share/nginx/html/

