version: "3"

services:
  db:
    image: postgres
    env_file:
      - ./backend/.env.dev
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis_db:
    image: redis
  backend:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile.dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./backend/.env.dev
    volumes:
      - ./backend/:/src/
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis_db
  front:
    build:
      context: .
      dockerfile: ./frontend/docker/Dockerfile.dev
    command: npm run dev
    volumes:
      - ./frontend/calories/:/src/
    ports:
      - 5173:5173
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./static/:/home/project/static/
    ports:
      - 9000:80
    depends_on:
      - backend
      - front

volumes:
  pg_data:
