FROM nginx:1.25.2

WORKDIR /home/project/

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx/nginx.prod.conf /etc/nginx/nginx.conf
COPY ./nginx/calorium.ru.crt /etc/nginx/
COPY ./nginx/calorium.ru.key /etc/nginx/
