FROM nginx:1.25.2

WORKDIR /home/project/

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx/nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/calorium.ru.crt /usr/local/nginx/conf/
COPY ./nginx/calorium.ru.key /usr/local/nginx/conf/
