FROM python:3.11

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /src

RUN pip install -U poetry
RUN poetry config virtualenvs.create false

COPY backend/pyproject.toml backend/poetry.lock /src/

RUN poetry install --no-interaction --no-ansi
